# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Step Description
        run: echo "Building docker image."
  deploy-dev:
    runs-on: docker
  needs: [build-docker-image]
    steps:
      - name: Print output
        run: echo Deploying application
  api-integration-test:
    runs-on: docker
    needs: [deploy-dev]
    steps:
      - name: Print output
        run: echo Testing Application
  
  