# This is a basic workflow to help you get started with Actions

name: Simple pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t martinowl/api-tests:latest . 
      
      - name: Push image
        run: docker push martinowl/api-tests:latest
  
  